# Menggunakan Node.js base image
FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

RUN apk add --no-cache \
  python3 \
  make \
  g++ \
  cairo-dev \
  pango-dev \
  jpeg-dev \
  giflib-dev \
  pixman-dev

# Copy package.json dan lock file
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .
# Build TypeScript (pastikan ada tsconfig.json)
RUN npm run build
# Expose port aplikasi
EXPOSE 4000
# Jalankan aplikasi
CMD ["node", "dist/index.js"]
