"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { usersApi } from "@/lib/api/erp/users.api";

type Permission = { id: string; code: string; name: string; module: string; description?: string | null };
type Role = { id: string; code: string; name: string; description?: string | null; isSystem: boolean; isSuperadmin: boolean; permissionCodes: string[] };
const blankRole = { code: "", name: "", description: "", isSuperadmin: false, permissionCodes: [] as string[] };
const blankPermission = { code: "", name: "", module: "", description: "" };

export default function RolesPermissionsClient() {
  const [roles, setRoles] = useState<Role[]>([]); const [permissions, setPermissions] = useState<Permission[]>([]);
  const [roleForm, setRoleForm] = useState(blankRole); const [permissionForm, setPermissionForm] = useState(blankPermission);
  const [editingRole, setEditingRole] = useState<Role | null>(null); const [editingPermission, setEditingPermission] = useState<Permission | null>(null);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const reload = async () => { const [roleData, permissionData] = await Promise.all([usersApi.roleDetails(), usersApi.permissions()]); setRoles(roleData); setPermissions(permissionData); };
  useEffect(() => { reload().catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const modules = useMemo(() => permissions.reduce<Record<string, Permission[]>>((groups, permission) => { (groups[permission.module] ??= []).push(permission); return groups; }, {}), [permissions]);
  const resetRole = () => { setEditingRole(null); setRoleForm(blankRole); };
  const resetPermission = () => { setEditingPermission(null); setPermissionForm(blankPermission); };
  const saveRole = async (event: FormEvent) => { event.preventDefault(); setError(""); try { if (editingRole) await usersApi.updateRole(editingRole.id, roleForm); else await usersApi.createRole(roleForm); setNotice("Role berhasil disimpan."); resetRole(); await reload(); } catch (e) { setError(e instanceof Error ? e.message : "Gagal menyimpan role"); } };
  const savePermission = async (event: FormEvent) => { event.preventDefault(); setError(""); try { if (editingPermission) await usersApi.updatePermission(editingPermission.id, permissionForm); else await usersApi.createPermission(permissionForm); setNotice("Permission berhasil disimpan."); resetPermission(); await reload(); } catch (e) { setError(e instanceof Error ? e.message : "Gagal menyimpan permission"); } };
  const editRole = (role: Role) => { setEditingRole(role); setRoleForm({ code: role.code, name: role.name, description: role.description ?? "", isSuperadmin: role.isSuperadmin, permissionCodes: role.permissionCodes }); };
  const editPermission = (permission: Permission) => { setEditingPermission(permission); setPermissionForm({ code: permission.code, name: permission.name, module: permission.module, description: permission.description ?? "" }); };
  const togglePermission = (code: string) => setRoleForm((form) => ({ ...form, permissionCodes: form.permissionCodes.includes(code) ? form.permissionCodes.filter((item) => item !== code) : [...form.permissionCodes, code] }));
  return <div className="grid gap-6 2xl:grid-cols-[430px_1fr]">
    <form onSubmit={saveRole} className="h-fit rounded-xl bg-white p-5 shadow-sm">
      <div className="flex items-center justify-between"><h2 className="font-bold">{editingRole ? "Edit role" : "Buat role"}</h2>{editingRole && <button type="button" onClick={resetRole} className="text-sm text-emerald-700">Batal</button>}</div>
      <div className="mt-4 grid gap-3 text-sm"><label>Code role<input required disabled={editingRole?.isSystem} value={roleForm.code} onChange={(e) => setRoleForm({ ...roleForm, code: e.target.value })} placeholder="inventory_manager" className="mt-1 w-full rounded border p-2 disabled:bg-slate-100" /></label><label>Nama<input required value={roleForm.name} onChange={(e) => setRoleForm({ ...roleForm, name: e.target.value })} className="mt-1 w-full rounded border p-2" /></label><label>Deskripsi<textarea value={roleForm.description} onChange={(e) => setRoleForm({ ...roleForm, description: e.target.value })} className="mt-1 w-full rounded border p-2" /></label>
        <label className="flex gap-2 rounded border border-violet-200 bg-violet-50 p-3"><input type="checkbox" checked={roleForm.isSuperadmin} onChange={(e) => setRoleForm({ ...roleForm, isSuperadmin: e.target.checked })} /><span><b>Superadmin access</b><small className="block text-slate-600">Akses penuh tanpa mengecek permission.</small></span></label>
      </div><button className="mt-5 w-full rounded bg-emerald-700 px-4 py-2 font-semibold text-white">Simpan role</button>
    </form>
    <section className="space-y-6"><div className="overflow-hidden rounded-xl bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Role access matrix</h2><p className="mt-1 text-sm text-slate-500">Centang kemampuan CRUD per modul. Superadmin mengabaikan matriks ini.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left">Role</th><th className="px-4 py-3 text-left">Level</th><th className="px-4 py-3 text-left">Permissions</th><th className="px-4 py-3">Aksi</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="p-6 text-center">Memuat...</td></tr> : roles.map((role) => <tr key={role.id} className="border-t"><td className="px-4 py-3"><b>{role.name}</b><small className="block text-slate-500">{role.code}</small></td><td className="px-4 py-3">{role.isSuperadmin ? <span className="rounded-full bg-violet-100 px-2 py-1 text-violet-800">Super admin</span> : "Permission based"}</td><td className="px-4 py-3 text-slate-600">{role.permissionCodes.length ? `${role.permissionCodes.length} izin dipilih` : "Tidak ada"}</td><td className="px-4 py-3 text-right"><button type="button" onClick={() => editRole(role)} className="text-emerald-700">Edit</button>{!role.isSystem && <button type="button" onClick={async () => { if (confirm(`Hapus role ${role.name}?`)) { await usersApi.removeRole(role.id); await reload(); } }} className="ml-3 text-red-600">Hapus</button>}</td></tr>)}</tbody></table></div></div>
      <div className="rounded-xl bg-white p-5 shadow-sm"><h2 className="font-bold">Atur permission untuk {editingRole?.name ?? "role baru"}</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{Object.entries(modules).map(([module, entries]) => <fieldset key={module} className="rounded-lg border p-3"><legend className="px-1 text-sm font-bold capitalize">{module}</legend>{entries.map((permission) => <label key={permission.id} className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={roleForm.permissionCodes.includes(permission.code)} onChange={() => togglePermission(permission.code)} /><span>{permission.name}<small className="ml-2 text-slate-400">{permission.code}</small></span></label>)}</fieldset>)}</div></div>
      <form onSubmit={savePermission} className="rounded-xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Permission catalog</h2>{editingPermission && <button type="button" onClick={resetPermission} className="text-sm text-emerald-700">Batal</button>}</div><div className="mt-3 grid gap-3 md:grid-cols-4"><input required placeholder="Code: materials.update" value={permissionForm.code} onChange={(e) => setPermissionForm({ ...permissionForm, code: e.target.value })} className="rounded border p-2" /><input required placeholder="Nama permission" value={permissionForm.name} onChange={(e) => setPermissionForm({ ...permissionForm, name: e.target.value })} className="rounded border p-2" /><input required placeholder="Modul" value={permissionForm.module} onChange={(e) => setPermissionForm({ ...permissionForm, module: e.target.value })} className="rounded border p-2" /><button className="rounded bg-slate-800 px-4 py-2 font-semibold text-white">{editingPermission ? "Update" : "Tambah"} permission</button></div><input placeholder="Deskripsi (opsional)" value={permissionForm.description} onChange={(e) => setPermissionForm({ ...permissionForm, description: e.target.value })} className="mt-3 w-full rounded border p-2" /></form>
      <div className="overflow-hidden rounded-xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Code</th><th className="p-3 text-left">Nama</th><th className="p-3 text-left">Modul</th><th className="p-3 text-right">Aksi</th></tr></thead><tbody>{permissions.map((permission) => <tr key={permission.id} className="border-t"><td className="p-3 font-mono text-xs">{permission.code}</td><td className="p-3">{permission.name}</td><td className="p-3">{permission.module}</td><td className="p-3 text-right"><button type="button" onClick={() => editPermission(permission)} className="text-emerald-700">Edit</button><button type="button" onClick={async () => { if (confirm(`Hapus permission ${permission.code}?`)) { await usersApi.removePermission(permission.id); await reload(); } }} className="ml-3 text-red-600">Hapus</button></td></tr>)}</tbody></table></div></div>
    </section>{(error || notice) && <p className={`fixed bottom-5 right-5 rounded px-4 py-3 shadow ${error ? "bg-red-600 text-white" : "bg-emerald-600 text-white"}`}>{error || notice}</p>}
  </div>;
}
